spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lord_of_the_ring
    username: root
    password: 7113395
  jpa.:
    hibernate:
      ddl-auto: create
      show-sql: true