spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hello_jpa
    username: root
    password: 7113395
  jpa.:
    hibernate:
      ddl-auto: create
    show-sql: true